security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        # Public read-only
        - { path: ^/api/touits, roles: PUBLIC_ACCESS, methods: [ GET ] }
        # Private write
        - { path: ^/api/touits, roles: IS_AUTHENTICATED_FULLY, methods: [ POST, DELETE ] }
